GoogleCloudPlatform/appengine-plugins

.travis.yml

@joaoandremartins as discussed in yesterday's meeting

turn on travis

---

pom.xml
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineDeployment.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineDeploymentTest.java

During refactoring I broke the "depoy" command by changing it to "cloud" accidentally. This fixes it.
Also, there is a performance issue with maven-jar-plugin when used with Java 7 that this fixes.
@loosebazooka  PTAL

Fix deploy command and improve build speed

---

src/main/java/com/google/cloud/tools/app/impl/appcfg/AppCfgAppEngineStandardStaging.java
src/main/java/com/google/cloud/tools/app/impl/appcfg/AppEngineSdk.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/PathResolver.java

Use File instead of Path everywhere

---

src/main/java/com/google/cloud/tools/app/api/deploy/DeployConfiguration.java
src/main/java/com/google/cloud/tools/app/api/deploy/StageStandardConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/appcfg/AppCfgAppEngineStandardStaging.java
src/main/java/com/google/cloud/tools/app/impl/appcfg/AppEngineSdk.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineDeployment.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultDeployConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultStageStandardConfiguration.java
src/test/java/com/google/cloud/tools/app/AppCfgAppEngineStandardStagingTest.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineDeploymentTest.java

change config param applicationID to application
change -A to --application

Correct stage task parameter order and update stage and deploy configurations

---

pom.xml

@meltsufin setting up to publish to sonatype snapshot repository

Set version to 0.1.0-SNAPSHOT for publishing

---

src/main/java/com/google/cloud/tools/app/api/deploy/StageStandardConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineStandardStaging.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultStageStandardConfiguration.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineStandardStagingTest.java

remove version from stage

---

pom.xml
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineDeployment.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineModuleService.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineStandardStaging.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineStandardStagingTest.java

Use cloudsdk appcfg

---

pom.xml

add Maven Central Snapshots repository for distribution

---

src/main/java/com/google/cloud/tools/app/api/AppEngineException.java

Make AppEngineException unchecked

---

src/main/java/com/google/cloud/tools/app/api/deploy/DeployConfiguration.java
src/main/java/com/google/cloud/tools/app/api/deploy/StageStandardConfiguration.java
src/main/java/com/google/cloud/tools/app/api/devserver/RunConfiguration.java
src/main/java/com/google/cloud/tools/app/api/genconfig/GenConfigParams.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineDeployment.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineDevServer.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineFlexibleStaging.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineGenConfig.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineModuleService.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineStandardStaging.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/util/Args.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultDeployConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultGenConfigParams.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultRunConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultStageStandardConfiguration.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineDeploymentTest.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineDevServerTest.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineGenConfigTest.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineStandardStagingTest.java

- Allowing null option to delegate to the underlying tool to
respect its defaults (false OR true)
- Explicitly pass true and false values to boolean flags

Change boolean to Boolean

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/PathResolver.java

Automatically resolve Cloud SDK path when none is provided

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java

See #45 
@loosebazooka @meltsufin what do you think about something like this? I only added usage of the common configuration to CloudSdkAppEngineDeployment for now, but you get the idea.

Add common configuration

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineDeployment.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineModuleService.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java
src/test/java/com/google/cloud/tools/app/CloudSdkAppEngineDeploymentTest.java

Move quiet flag to sdk app cmd level

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java

Add a Builder to the CloudSdk class

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/util/Args.java

Credential file override flag support

---

pom.xml

I've put `.java` into the bundle name.

Use maven-bundle-plugin to add OSGi metadata to consume within Eclipse

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/DefaultProcessRunner.java

Fixes #57 allowing clients to destroy an executing process.

Expose the current running process in DefaultProcessRunner

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/DefaultProcessRunner.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/ProcessRunner.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java

fixes #39 
@loosebazooka @meltsufin, thoughts?

Add environment variable setters to cloudsdk builder

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java

Attempt to address the goals of #68 building on top of #67.
@loosebazooka @etanshaul PTAL

Proxy ProcessRunnner configuration in CloudSdk.Builder

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/DefaultProcessRunner.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/ProcessStartListener.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java

Fixes #77 
@loosebazooka @etanshaul

Add a listener to give access to process

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineStandardStaging.java

Copy dockerfile into source directory before staging

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineFlexibleStaging.java

Ensure docker can read artifacts in flexible deploys

---

src/main/java/com/google/cloud/tools/app/api/Configuration.java
src/main/java/com/google/cloud/tools/app/api/DefaultConfiguration.java
src/main/java/com/google/cloud/tools/app/api/deploy/DeployConfiguration.java
src/main/java/com/google/cloud/tools/app/api/instances/InstancesSelectionConfiguration.java
src/main/java/com/google/cloud/tools/app/api/logs/LogsConfiguration.java
src/main/java/com/google/cloud/tools/app/api/services/ServicesSelectionConfiguration.java
src/main/java/com/google/cloud/tools/app/api/versions/VersionsListConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineDeployment.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineInstances.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineLogs.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineServices.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineVersions.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/args/GcloudArgs.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultDeployConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultInstancesSelectionConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultLogsConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultServicesSelectionConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultTrafficSplitConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultVersionsListConfiguration.java
src/main/java/com/google/cloud/tools/app/impl/config/DefaultVersionsSelectionConfiguration.java
src/test/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineDeploymentTest.java
src/test/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineInstancesTest.java
src/test/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineLogsTest.java
src/test/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineServicesTest.java
src/test/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineVersionsTest.java
src/test/java/com/google/cloud/tools/app/impl/cloudsdk/internal/args/GcloudArgsTest.java

fixes #97
@loosebazooka, @meltsufin 
I only added it to a couple commands for now (stop, start).

Add project to common configuration

---

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/DefaultProcessExitListener.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/DefaultProcessRunner.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/NonZeroExceptionExitListener.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/ProcessExitListener.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/ProcessOutputLineListener.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/ProcessStartListener.java
src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/WaitingProcessOutputLineListener.java

Renames listener methods to use the onSomething naming convention

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

Only set CLOUDSDK_APP_USE_GSUTIL if credentials are being overridden

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunnerTest.java

Fixes #122.
@loosebazooka  PTAL

Fix command generation for Windows

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

Fixes #118.
@loosebazooka @briandealwis PTAL

Restore CloudSdk.validate()

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/AppCfgArgs.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/Args.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/DevAppServerArgs.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServerTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/AppCfgArgsTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/DevAppServerArgsTest.java

Fixes #121.
@nbashirbello @loosebazooka PTAL

Fix dev_appserver arguments syntax

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeployment.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java

@meltsufin open to suggestions on different ways to do this, basically if we get a directory, then look through it for yamls

Yaml search through deployable directory

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

Make sure we pass format flag to gcloud

---

README.md
pom.xml
src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/DefaultProcessExitListener.java

Prepare pom.xml for release to Maven Central

---

.gitignore
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

@meltsufin 
also added some eclipse metadata to the .gitginore

expose path to appengine jars

---

pom.xml

...following the 0.1.0 release.

Bump current version to 0.1.1-SNAPSHOT

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStaging.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStagingTest.java

Fix dockerfile copying for standard staging

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

remove unused field

---

pom.xml

Bump to 0.1.2-SNAPSHOT

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeployment.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java

This reverts commit 5a0914c7ba7d851fbca8bc31c5ebee000ed9538f.

Revert "Yaml search through deployable directory (#128)"

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

Use gcloud-app command instead of gcloud-preview-app

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/WaitingProcessOutputLineListener.java

- adds exitListener/startListener lists

Make dev_appserver exit in asnyc on failure

---

pom.xml

version to 0.1.4

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/WaitingProcessOutputLineListener.java

Fix detection of asynchronous start of dev appserver for compat apps

---

pom.xml

Bump current version to 0.1.5-SNAPSHOT following the 0.1.4 release

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java

Fail flexible staging when artifact does not exist

---

.travis.yml
.travis/settings.xml

Configure Travis to Deploy Snapshots on commit to master

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java

Wanted to create unit tests for DefaultProcessRunner but Mockito can't mock ProcessBuilder and I don't want to use PowerMock.

Adds flag to disable stdout and stderr inheritance by subprocesses.

---

pom.xml

Bump version to 0.1.6-SNAPSHOT following release of 0.1.5

---

pom.xml
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java

look for python in more places on windows

---

README.md

appengine-plugins-core-*version*-SNAPSHOT.jar

---

pom.xml

Bump current version to 0.1.7-SNAPSHOT following 0.1.6 release

---

pom.xml

Use appengine-plugins-core in URLs

---

pom.xml

update OSGI bundle name

---

pom.xml

Bump version to 0.1.8-SNAPSHOT following 0.1.7 release

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/AppEngineJavaComponentsNotInstalledException.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

more specific exception when app engine java components are not installed

---

pom.xml

Bump current version to 0.1.9-SNAPSHOT following 0.1.8 release

---

checkstyle-suppressions.xml
src/main/java/com/google/cloud/tools/project/ProjectIdValidator.java
src/main/java/com/google/cloud/tools/project/package-info.java
src/test/java/com/google/cloud/tools/project/ProjectIdValidatorTest.java

@akerekes @meltsufin 
I want to move this code out of Eclipse. 
This introduces a new package structure above app engine since this projects and project IDs are not limited to App Engine.
see https://github.com/GoogleCloudPlatform/cloud-tools-for-eclipse/issues/666

Project ID validator

---

src/main/java/com/google/cloud/tools/appengine/api/versions/DefaultVersionsListConfiguration.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java

fix warnings

---

pom.xml

Bump current version to 0.1.10-SNAPSHOT following 0.1.9 release

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

Fixes #217.
@etanshaul @patflynn @loosebazooka @elharo

Enable quiet mode for dev appserver and auto-install app-engine-java

---

pom.xml

Bump to 0.1.11-SNAPSHOT following 0.1.10 release

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java

Update comment in CloudSdkAppEngineFlexibleStaging.java

---

pom.xml

Bump version to 0.1.13-SNAPSHOT following release of 0.1.12

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/AppCfgArgs.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/Args.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/DevAppServerArgs.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/GcloudArgs.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServerTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/DevAppServerArgsTest.java

Required for the dev_appserver automatic_restart flag, which is set to `true` by default. Setting this flag explicitly to false is required.
Helps in https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/972

Adds support for '--name=true/false' flags.

---

pom.xml

Bump to 0.2.1-SNAPSHOT after performing 0.2.0 release.

Bump to 0.2.1-SNAPSHOT

---

src/main/java/com/google/cloud/tools/io/FilePermissions.java
src/test/java/com/google/cloud/tools/io/FilePermissionsTest.java

@akerekes @briandealwis @meltsufin as requested, I've pulled these out into an independent, tested utility.
After this bakes a bit more, I want to push this all the way up to Guava, but that's not going to happen on our time frame.

File Utilities that don't depend on eclipse

---

.travis.yml
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkNotFoundException.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkOutOfDateException.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java

@briandealwis @aslo Anything less than 131 causes issues.

check for minimum required Cloud SDK version

---

.travis.yml
src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/PathResolverTest.java

Check Windows per-user install

---

src/main/java/com/google/cloud/tools/project/ServiceNameValidator.java
src/test/java/com/google/cloud/tools/project/ServiceNameValidatorTest.java

@briandealwis We'll need this or something like it to add service names to our new application wizards

validator for App Engine service (a.k.a. module) names

---

.gitignore

ignore eclipse neon .metadata

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

@briandealwis also uses a more specific exception

It's the Cloud SDK that is not found, not the Cloud SDK path.

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkNotFoundException.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java

@chanseokoh It's not immediately clear to me why sometimes reading the versions returns the empty string.

throw exception if we can't read version

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/StringBuilderProcessOutputLineListener.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/ProcessOutputLineListener.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
src/test/java/com/google/cloud/tools/appengine/experimental/process/CliProcessManagerTest.java

@joaoandremartins @meltsufin @briandealwis @chanseokoh

add test for getVersion

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

Flag had no effect at the end of the gcloud command.

Places quiet flag in right place.

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

~~fix #279~~ @chanseokoh
UPDATE(@chanseokoh): helps with #279.

add exception javadoc

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServerTest.java

Fail sooner on null SDK

---

src/main/java/com/google/cloud/tools/io/FilePermissions.java
src/test/java/com/google/cloud/tools/io/FilePermissionsTest.java

more accurate exceptions

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeployment.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java

better javadoc, and precondition checking for CloudSdkAppEngineDeployment

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkOutOfDateException.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkOutOfDateExceptionTest.java

Include installed version of the Cloud SDK

---

.travis.yml

@chanseokoh see https://codecov.io/gh/GoogleCloudPlatform/appengine-plugins-core/tree/148ed073572ac05cffede218e5f24ee5932812c4/src/main/java/com/google/cloud/tools for an example of what this is producing

run cobertura

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java

Managed VMs to flex

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineGenConfig.java

fixed javadoc

---

src/main/java/com/google/cloud/tools/appengine/api/devserver/DefaultRunConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/devserver/RunConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/whitelist/AppEngineJreWhitelist.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServerTest.java

Also fix some minor checkstyle issue

Add clearDatastore flag

---

checkstyle-suppressions.xml
src/main/java/com/google/cloud/tools/appengine/AppEngineDescriptor.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineGenConfig.java
src/test/java/com/google/cloud/tools/appengine/AppEngineDescriptorTest.java

@chanseokoh Copied from CT4E
Also suppresses outdated import order rules

Add AppEngineDescriptor class

---

pom.xml

0.2.6 is expected to show up today.

Bump to 0.2.7-SNAPSHOT after releasing 0.2.6

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionPreRelease.java
src/main/java/com/google/cloud/tools/appengine/experimental/internal/cloudsdk/CloudSdkV2.java
src/main/java/com/google/cloud/tools/appengine/experimental/internal/process/CliProcessManager.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineInstancesTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineVersionsTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkComponentTest.java
src/test/java/com/google/cloud/tools/appengine/experimental/AppEngineRequestsTest.java

fix assorted warnings

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeployment.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/ProcessRunner.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java

Support staging directory as a single deployable

---

pom.xml
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java
src/main/java/com/google/cloud/tools/project/AppYaml.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStagingTest.java
src/test/java/com/google/cloud/tools/project/AppYamlTest.java
src/test/java/com/google/cloud/tools/test/utils/LogStoringHandler.java

Add warning when runtime = java and docker directory isn't empty

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStagingTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/PathResolverTest.java
src/test/java/com/google/cloud/tools/test/utils/LogStoringHandler.java

What do you guys think of something like this for path resolution for the case
```
~/bin/gcloud -> ~/my-custom-software-location/google-cloud-sdk/bin/gcloud
```
This is a rough PR for #267 , not expected to submit in this form.

Follow symlinks on gcloud to cloudsdk

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java

upgrade minimum SDK version

---

README.md

add BUILD status badge

---

pom.xml

require dependency convergence

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java

Avoid possible NPE

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
src/test/java/com/google/cloud/tools/io/FilePermissionsTest.java

test fixes for Windows build failures

Win build fixes

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/StringBuilderProcessOutputLineListener.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/StringBuilderProcessOutputLineListenerTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/process/StringBuilderProcessOutputLineListenerTest.java

Move StringBuilderProcessOutputLineListener out of internal 

---

src/main/java/com/google/cloud/tools/appengine/api/devserver/DefaultRunConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/devserver/RunConfiguration.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServerTest.java

Remove `RunConfiguration.appYamls` and use `RunConfiguration.services` instead.

Fixes #367 - appYamls vs Services

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java

@chanseokoh @loosebazooka fix #370

allow non default admin port

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java

also alphabetize some parameters

Remove datastore options for devappserver1

---

src/main/java/com/google/cloud/tools/io/FileUtil.java
src/test/java/com/google/cloud/tools/io/FileUtilTest.java

Google style is not to use ExpectedException

---

src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStagingTest.java

remove some more expected exceptions

---

kokoro/continuous.bat

remove gcloud and mvn installation from win build script, rely on the existing ones in the VM

Fixes #394 - kokoro tests broken 

---

src/main/java/com/google/cloud/tools/project/AppYaml.java

Close file with try-with-resources / use Files.newInputStream() instead of FileReader()

---

pom.xml

Release process done; 0.3.3 will be available publicly in a couple hours.

Bump to 0.3.4-SNAPSHOT after 0.3.3 release

---

src/main/java/com/google/cloud/tools/project/AppYaml.java
src/test/java/com/google/cloud/tools/project/AppYamlTest.java

Fix NPE in getRuntime() when empty app.yaml

---

src/main/java/com/google/cloud/tools/appengine/api/deploy/DefaultDeployProjectConfigurationConfiguration.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineGenConfig.java
src/main/java/com/google/cloud/tools/appengine/experimental/internal/cloudsdk/CloudSdkRequest.java
src/main/java/com/google/cloud/tools/appengine/experimental/internal/process/CliProcessManager.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer2Test.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStagingTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStagingTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
src/test/java/com/google/cloud/tools/appengine/experimental/internal/cloudsdk/CloudSdkRequestTest.java
src/test/java/com/google/cloud/tools/io/FileUtilTest.java

various warnings fixes

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineGenConfig.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineInstances.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineLogs.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineServices.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineVersions.java

better exception JavaDoc

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java

fail earlier

---

pom.xml

Post release v0.3.4 0.3.5-SNAPSHOT

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java

@chanseokoh This has the side effect of fixing the OSGI classpath problem.

convert YAML exception to AppEngineException

---

pom.xml

@loosebazooka @chanseokoh update to 0.3.6-SNAPSHOT

post release 0.3.5

---

kokoro/continuous_mac.sh

@elharo trying to see if this fixes our macos build.

Use pre-installed gcloud on macos

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java

@loosebazooka @lesv and fix up the owners for the commit log

Better handling of invalid paths

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/PathResolverTest.java

@lesv @chanseokoh @loosebazooka

unquote paths on Windows

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java

Add support for automatic-restart for CloudSdkAppEngineDevServer1

---

pom.xml
src/main/java/com/google/cloud/tools/libraries/libraries.json
src/main/java/com/google/cloud/tools/libraries/libraries.xml
src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java
src/test/java/com/google/cloud/tools/libraries/libraries.xml

@patflynn @loosebazooka @briandealwis @chanseokoh Here's a straw man sample of what generic API client library metadata might look like.

strawman API metadata format

---

src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java

@loosebazooka @chanseokoh check that URLs are not 404

check URLs are reachable

---

src/main/java/com/google/cloud/tools/libraries/libraries.json
src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java

@briandealwis @loosebazooka  @patflynn @etanshaul got a bit confused by the capitalization, but this is the current branch

Add remaining metadata

---

pom.xml
src/main/java/com/google/cloud/tools/managedcloudsdk/internal/download/DownloadProgressListener.java
src/main/java/com/google/cloud/tools/managedcloudsdk/internal/download/Downloader.java
src/main/java/com/google/cloud/tools/managedcloudsdk/internal/download/DownloaderFactory.java
src/main/java/com/google/cloud/tools/managedcloudsdk/internal/download/StandardDownloader.java
src/test/java/com/google/cloud/tools/managedcloudsdk/internal/download/StandardDownloaderTest.java

First part of the Cloud SDK manager code is the downloader. The first few PRs will all just be generic functionality to keep commits small. Once that's done, we'll stitch it all together.

Downloader component of Managed Cloud SDK.

---

pom.xml

preparing release 0.3.7

---

.travis.yml

this _JAVA_OPTIONS thing is messing with us : https://github.com/travis-ci/travis-ci/issues/8408

fix travis build that was erroring

---

pom.xml

bundle libraries.json

---

src/main/java/com/google/cloud/tools/libraries/CloudLibraries.java
src/main/java/com/google/cloud/tools/libraries/json/CloudLibrary.java
src/main/java/com/google/cloud/tools/libraries/json/CloudLibraryClient.java
src/main/java/com/google/cloud/tools/libraries/json/CloudLibraryClientMavenCoordinates.java
src/test/java/com/google/cloud/tools/libraries/CloudLibrariesTest.java
src/test/java/com/google/cloud/tools/libraries/json/CloudLibraryTest.java

This will either be here, next to the `libraries.json` file and synchronized with the changes made to the JSON, or it would need to live independently in the IntelliJ plugin, so I opted to place it here. Feel free to suggest different approaches as well.

Adds utility classes around the libraries.json file

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json
src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java

Add service name to json client lib metadata

---

scripts/prepare_release.sh

Limits pushing of release tag to not include any other local tags.

---

pom.xml

Release 0.3.10

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

@etanshaul @loosebazooka fix #498

add firestore and upgrade to 0.30.0

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkComponent.java
src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java
src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedSdkVerificationException.java
src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedSdkVersionMismatchException.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkComponentTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkIntegrationTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java

Depends on #502, look at that first, then this. This is configured to merge into that branch (processHandlingAbstractions), I'll update the pull request after that's ready.

Provides an entry point into the Managed SDK mechanism.

---

src/main/java/com/google/cloud/tools/libraries/json/CloudLibrary.java
src/test/java/com/google/cloud/tools/libraries/json/CloudLibraryTest.java

Follow up to #483 and #485 
Exposes the new metadata in the json binding

Expose service-name and service-roles in the CloudLibrary json binding

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

@loosebazooka @etanshaul fix #522

upgrade to 0.33

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

update to 0.35.0-alpha

---

pom.xml

Update to guava21, cleanup todos

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

@chanseokoh @loosebazooka @etanshaul

update google-cloud-java libraries

---

pom.xml

This one with fix for the SDK install/update issue on Windows.

Preparing release 0.5.1

---

pom.xml

@briandealwis @loosebazooka fix #236

OSGI doc URL

---

pom.xml
src/main/java/com/google/cloud/tools/appengine/AppEngineDescriptor.java
src/main/java/com/google/cloud/tools/appengine/api/AppEngineException.java
src/main/java/com/google/cloud/tools/appengine/api/debug/GenRepoInfoFile.java
src/main/java/com/google/cloud/tools/appengine/api/logs/AppEngineLogs.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeployment.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineInstances.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineLogs.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkGenRepoInfoFile.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/NonZeroExceptionExitListener.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/ProcessExitListener.java
src/test/java/com/google/cloud/tools/appengine/AppEngineDescriptorTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStagingTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineInstancesTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineLogsTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineServicesTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineVersionsTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkGenRepoInfoFileTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/process/NonZeroExceptionExitListenerTest.java

@loosebazooka @chanseokoh fix #84

revert AppEngineException to checked

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

@loosebazooka update library versions to 0.41.0

BigQuery is GA

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json
src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java

@loosebazooka @etanshaul fix #526 
I cleaned up the names, alphabetized what was left, and updated some versions.

Order APIs

---

src/test/java/com/google/cloud/tools/appengine/cloudsdk/process/LegacyProcessHandlerTest.java

unused variables

---

pom.xml

Spelling typos

---

pom.xml
src/test/java/com/google/cloud/tools/managedcloudsdk/components/SdkUpdaterTest.java

Upgrade errorprone; not clear why null issues don't seem to be firing.

Errorprone

---

src/main/java/com/google/cloud/tools/managedcloudsdk/install/Extractor.java
src/main/java/com/google/cloud/tools/managedcloudsdk/install/ExtractorFactory.java
src/main/java/com/google/cloud/tools/managedcloudsdk/install/FileResourceProviderFactory.java
src/main/java/com/google/cloud/tools/managedcloudsdk/install/Installer.java
src/main/java/com/google/cloud/tools/managedcloudsdk/install/InstallerFactory.java
src/main/java/com/google/cloud/tools/managedcloudsdk/install/ZipExtractorProvider.java
src/test/java/com/google/cloud/tools/managedcloudsdk/ChildProgressListenerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/command/AsyncByteConsumerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/command/CommandCallerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/command/CommandRunnerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/components/SdkComponentInstallerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/components/SdkUpdaterTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/components/WindowsBundledPythonCopierTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/DownloaderTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/ExtractorFactoryTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/ExtractorTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/InstallerFactoryTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/InstallerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/SdkInstallerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/TarGzExtractorProviderTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/ZipExtractorProviderTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/process/ProcessExecutorTest.java

I'm fine backing off some if you don't like them.

Code cleanup

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStaging.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/LegacyProcessHandler.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/StringBuilderProcessOutputLineListener.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionPreRelease.java
src/main/java/com/google/cloud/tools/libraries/CloudLibraries.java
src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java
src/main/java/com/google/cloud/tools/managedcloudsdk/Version.java
src/main/java/com/google/cloud/tools/managedcloudsdk/command/AsyncStreamHandlerFactory.java
src/main/java/com/google/cloud/tools/managedcloudsdk/command/AsyncStreamSaverFactory.java

@loosebazooka JSON defaults to UTF-8 fix #602

fix some errorprone warnings

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/AppEngineDeployResult.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/GcloudStructuredLog.java

Avoid conflict with java.lang.Error

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

Add two new APIs

---

src/main/java/com/google/cloud/tools/libraries/CloudLibraries.java
src/main/java/com/google/cloud/tools/managedcloudsdk/command/AsyncStreamSaverFactory.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/ExitCodeRecorderProcessExitListenerTest.java
src/test/java/com/google/cloud/tools/libraries/CloudLibrariesTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/VersionTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/command/AsyncByteConsumerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/command/CollectingByteHandlerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/DownloaderTest.java

fix warnings in tests

---

pom.xml
src/main/java/com/google/cloud/tools/io/FilePermissions.java
src/test/java/com/google/cloud/tools/io/FilePermissionsTest.java

throw NullPointerException

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

Update to 0.48.0 including adding web security scanner

---

pom.xml
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/Gcloud.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/GcloudRunner.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/AppCfgArgs.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/args/GcloudArgs.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/GcloudStructuredLog.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStagingTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAuthTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/LocalRunRunnerTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/PathResolverTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/ExitCodeRecorderProcessExitListenerTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkComponentTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/GcloudStructuredLogTest.java

More null checks

---

pom.xml

Update to SnakeYAML 1.21

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

fix #649 @etanshaul @loosebazooka 
FYI service roles are documented at https://cloud.google.com/iot/docs/how-tos/iam and in Cloud Console on **IAM & Admin > Roles** https://pantheon.corp.google.com/iam-admin/roles

Add IoT Core and promote Pubsub to GA

---

src/main/java/com/google/cloud/tools/appengine/api/deploy/StageFlexibleConfiguration.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java
src/test/java/com/google/cloud/tools/appengine/api/deploy/StageFlexibleConfigurationTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStagingTest.java

fix #660 @loosebazooka @chanseokoh

allow omitting docker directory

---

src/main/java/com/google/cloud/tools/project/AppYaml.java

Wrap all SnakeYAML exceptions in our `AppEngineException`.

Cause AppYaml#parse() to wrap all YAMLException as AppEngineException

---

src/main/java/com/google/cloud/tools/managedcloudsdk/command/AsyncByteConsumer.java
src/main/java/com/google/cloud/tools/managedcloudsdk/components/WindowsBundledPythonCopier.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/process/LegacyProcessHandlerTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/install/DownloaderTest.java

`PythonDeleter` was introduced temporarily at the time we were trying to use Cobertura.

Restore original code

---

pom.xml

@chanseokoh @loosebazooka fix #685

Inc. to LLC

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

fix #683 @etanshaul @loosebazooka 
Adds text-to-speech API

update google-cloud-java to 0.53.0

---

pom.xml

@loosebazooka @chanseokoh fix #669

update commons compress

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json
src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java

update libraries to 1.37.1

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStaging.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java

replace deprecated methods scheduled to be removed in January

---

pom.xml

upgrade to GSON 2.8.5

---

scripts/prepare_release.sh

remove unused Colorize method

---

pom.xml

fix #690 @loosebazooka @chanseokoh

upgrade to Guava 26.0-jre

---

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java

fix #708 @loosebazooka @patflynn In this case we were correctly noticing a bad release that was pulled. I'm not 100% sure we want to fix this. Arguably we did exactly what we should have done when faced with a bad push.

don't die on bad version string

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

fix #715 @etanshaul @chanseokoh

Update libraries to new organization and 0.66.0

---

pom.xml

Update commons-compress to 1.18

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

bump library versions

---

src/main/java/com/google/cloud/tools/appengine/api/deploy/DeployConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/deploy/DeployProjectConfigurationConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/deploy/StageFlexibleConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/deploy/StageStandardConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/devserver/RunConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/devserver/StopConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/versions/VersionsListConfiguration.java
src/main/java/com/google/cloud/tools/appengine/api/versions/VersionsSelectionConfiguration.java
src/test/java/com/google/cloud/tools/appengine/api/deploy/StageFlexibleConfigurationTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer2Test.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStagingTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineVersionsTest.java

Use value name directly on setter in builders

---

src/main/java/com/google/cloud/tools/io/FileUtil.java
src/test/java/com/google/cloud/tools/io/FileUtilTest.java

Adding this in so we can add support for staging accompanying files in a appengine directory like `src/main/appengine` without copying over other config yamls (cron.yaml, etc) 
cc: @ludoch

Add excludes to directory copy mechanism

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

Update to latest cloud libraries 
@loosebazooka

spanner 1.0.0

---

src/main/java/com/google/cloud/tools/appengine/api/deploy/AppEngineAppYamlStaging.java
src/main/java/com/google/cloud/tools/appengine/api/deploy/StageAppYamlConfiguration.java
src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineAppYamlStaging.java
src/test/java/com/google/cloud/tools/appengine/api/deploy/StageAppYamlConfigurationTest.java
src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineAppYamlStagingTest.java

- Naming: AppEngineArchiveStaging -> AppEngineAppYamlStaging
- Parameter: ExtraFilesDirectory -> ExtraFilesDirectories
FYI: This will affect the UI if you've implemented access to extraFilesDirectory already.
Would like one intellij and one eclipse team member to sign off please?

Update app.yaml based application staging

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

google-cloud-java 0.77.0

---

src/main/java/com/google/cloud/tools/appengine/operations/cloudsdk/serialization/CloudSdkVersion.java
src/main/java/com/google/cloud/tools/appengine/operations/cloudsdk/serialization/CloudSdkVersionPreRelease.java

mark classes final to avoid equals problems with subclasses

---

README.md

LocalRun to DevServers

---

src/main/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStaging.java
src/test/java/com/google/cloud/tools/test/utils/SpyVerifier.java

remove unused code

---

pom.xml

release 0.7.4

---

pom.xml

Interestingly the check fails.

check linkage

---

src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java

Update cloud sdk test version to a more recent one

---

src/main/java/com/google/cloud/tools/appengine/configuration/DeployConfiguration.java
src/main/java/com/google/cloud/tools/appengine/operations/Deployment.java
src/test/java/com/google/cloud/tools/appengine/operations/DeploymentTest.java

Allow deployments to use `alpha` or `beta` on `gcloud <mode> app deploy`

Add support for gcloudMode during Deploy

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

add Cloud Tasks

---

pom.xml

@loosebazooka @suztomo I need this for a demo at the API summit next week.

update linkage checker rule

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

add phishingprotection API

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

Add scheduler API

---

src/main/java/com/google/cloud/tools/appengine/operations/Gcloud.java
src/main/java/com/google/cloud/tools/appengine/operations/GcloudRunner.java
src/test/java/com/google/cloud/tools/appengine/operations/GcloudRunnerTest.java
src/test/java/com/google/cloud/tools/appengine/operations/GcloudTest.java

See: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/340

Add support for gcloud --flags-file

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

Add Talent API

---

src/main/java/com/google/cloud/tools/appengine/operations/CloudSdk.java
src/test/java/com/google/cloud/tools/appengine/operations/CloudSdkTest.java

@loosebazooka @chanseokoh @briandealwis  fix #795

minimum SDK version now 186.0.0

---

README.md

wording nits

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

@loosebazooka translate docs moved

update translate API

---

src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java
src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java

Fixes #822.
Hopefully this also fixes https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/818#issuecomment-578885673.

Fix test failures: LibrariesTest and ManagedCloudSdkTest

---

src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java

replace deprecated method

---

src/main/java/com/google/cloud/tools/appengine/operations/cloudsdk/internal/args/Args.java

fix warning about mixing types

---

pom.xml

deps: update commons-compress

---

src/main/java/com/google/cloud/tools/libraries/json/CloudLibrary.java
src/main/resources/com/google/cloud/tools/libraries/libraries.json
src/test/java/com/google/cloud/tools/libraries/json/CloudLibraryTest.java

Remove icon parameter from libraries

---

.github/workflows/unit-tests.yaml
kokoro/continuous.bat
kokoro/continuous.sh
kokoro/continuous_mac.sh

back out codecov.io

---

README.md

we no longer use travis

---

pom.xml

release v0.9.6

---

pom.xml

Upgrades plugins and adds errorprone JPMS workarounds

Compile-time Java 17 compatibility

---

pom.xml

release v0.9.7

---

pom.xml

release v0.9.8

---

pom.xml

release v0.9.9

---

src/main/resources/com/google/cloud/tools/libraries/libraries.json

This is a temporary fix to failed test in #898.

Update source links in libraries.json

---

.allstar/binary_artifacts.yaml

chore: ignore test JARs for allstar

---

kokoro/release_build.sh

Thank you for your interest in contributing! For general guidelines, please refer to
the [contributing guide](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/CONTRIBUTING.md).
Before submitting a pull request, please make sure to:
with your proposed change,
or [file a new issue](https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/new).
Fixes #<issue_number_goes_here> 🛠️

chore: Enable quiet mode for release script

---

kokoro/release_build.sh

Thank you for your interest in contributing! For general guidelines, please refer to
the [contributing guide](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/CONTRIBUTING.md).
Before submitting a pull request, please make sure to:
with your proposed change,
or [file a new issue](https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/new).
Fixes #925  🛠️

chore: Ignore FilePermissionsTest

---

pom.xml

Release v0.9.10

---

pom.xml

release v0.9.11

---

pom.xml

deps: Upgrade Guava to 32.1.2

---

pom.xml

Somehow [the automation job for 0.10.0](https://github.com/GoogleCloudPlatform/appengine-plugins-core/actions/runs/6354978584) didn't create a pull request.

Release v0.10.0

---

src/main/java/com/google/cloud/tools/managedcloudsdk/command/CommandExitException.java
src/test/java/com/google/cloud/tools/managedcloudsdk/command/CommandCallerTest.java

fix: show error log when command fails

---

.kokoro/common.sh
.kokoro/release_build.sh
.kokoro/stage.sh
app-gradle-plugin/build.gradle.kts
app-gradle-plugin/gradle.properties
app-maven-plugin/pom.xml
appengine-plugins-core/pom.xml
versions.txt

In this PR:
- Setup command to release gradle plugin.
- Setup gradle plugin version in versions.txt.

feat: release gradle plugin

---

.kokoro/stage.sh
app-gradle-plugin/build.gradle.kts

In this PR:
- Add sonatype repository in publising ([doc](https://github.com/gradle-nexus/publish-plugin/blob/master/README.md#kotlin-dsl)).

feat: add sonatype repo

---

.gitignore
.kokoro/stage.sh
app-gradle-plugin/build.gradle.kts

In this PR:
- Disable auto publishing of `java-gradle-plugin`, which causes duplicated uploads.
- Disable module metadata generation.
Debug [log](https://docs.google.com/document/d/1yeR6cJdbThwW_vLSdOF9bBnTwiUqnSioRHzqZGSEhIM/edit?pli=1&resourcekey=0-BYApK8YsMGcur0sw_6E58g&tab=t.0#bookmark=id.3addfeqjds7).

chore: remove multiple uploads
