GoogleCloudPlatform/appengine-plugins

pom.xml
Fixes #65.
I downgraded the maven-jar-plugin to 2.3 and not using the latest version of maven-source-plugin because these versions run much faster. 'mvn clean install' runs in less than 8 seconds now for me.
=> Adding source plugin and changing jar plugin version for performance

src/main/java/com/google/cloud/tools/app/impl/cloudsdk/CloudSdkAppEngineStandardStaging.java, src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/AsyncProcessStartWaiter.java, src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/DefaultProcessRunner.java, src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/ProcessRunnerException.java, src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/process/WaitingProcessOutputLineListener.java, src/main/java/com/google/cloud/tools/app/impl/cloudsdk/internal/sdk/CloudSdk.java
This fixes #60 which is about detecting when Dev App Server has started.
This also adds a builder to the DefaultProcesRunner.
Also fixes #63 
Notice that this adds a general mechanism for detecting when an asynchronously started operation has succeeded.
The clients are also no longer allowed to configure and provide the ProcessBuilder because if they set inheritIO to true, capturing output doesn't work. Instead, clients that need to consume the process output should use the ProcessOutputLineListener.
@loosebazooka @etanshaul
=> Allow waiting for successful start of async commands

.idea/codeStyleSettings.xml
Fixes #61.
Imported IntelliJ codestyle settings from here: https://github.com/google/styleguide/.
IntelliJ modified the original source after import, probably to fit the schema of the current version of the IDE.
=> Update codestyle with correct Java indent settings

pom.xml
Commit be94e074b8856751f4f9e77c41d6045a1900abb2 marked a field as `@Nullable`, which caused the generated OSGi metadata to include an `Import-Package: javax.annotation`.  `java.annotation.Nullable` is one of the annotations proposed by JSR 305, and whose implementation is provided by the FindBugs project in a OSGi bundle called `org.jsr-305`.  Unfortunately other bundles define `javax.annotation` and so we have a split package situation, which is never fun.
This patch adjusts the OSGi metadata-generation process to not remove the `javax.annotation` package from the required imports.  It turns out the JSR 305 annotations don't actually have to be present at runtime.  The only consequence  is that any attempts to fetch the annotations at runtime via `java.lang.reflect` will not see the JSR …
=> [OSGi] Avoid importing javax.annotation to prevent problems from split packages

src/main/java/com/google/cloud/tools/appengine/api/deploy/DefaultStageFlexibleConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/StageFlexibleConfiguration.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java
Fixes #96. 
The clients now have to specify an App Engine config directory instead of an app.yaml path for flexible staging.
=> Copy all App Engine supported files for staging

src/main/java/com/google/cloud/tools/appengine/api/deploy/DefaultStageStandardConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/StageStandardConfiguration.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStaging.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStagingTest.java
=> Add support for java8 in standard staging.

README.md, pom.xml
=> Bump version to 0.1.3-SNAPSHOT

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStaging.java
This is a change that we should push up to appcfg/staging or into
gcloud. No tool at the moment appears to be building a dockerfile
with runtime:java and vm:true that is correct. By forcing the jdk
to be openjdk8 we trigger the creation of a Dockerfile with the
correct java8jetty9 image.
=> If runtime is java, set runtime config to openjdk8 in app.yaml

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
getSdkPath should only be used for testing in https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/pull/335
@meltsufin @loosebazooka PTAL
=> Make getSdkPath and getJavaToolsJar public.

findbugs-exclude.xml, pom.xml, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkResolver.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java
Currently the Eclipse Tooling has wrapper classes (`CloudSdkProvider` and `CloudSdkPrompter`) for resolving the Google Cloud SDK using a user-provided location.  This solution is error-prone as all code that tries to obtain a `CloudSdk` instance must funnel through these wrapper classes.  Failures occur if there are any code paths that uses the `CloudSdk.Builder` directly.
This patch extracts an interface `CloudSdkResolver` modelled on PathResolver.  The `CloudSdk` instance looks up additional `CloudSdkResolver` classes using the standard `java.util.ServiceLoader` mechanism.  To support registering resolvers under Eclipse, where we have separate class loaders, we register the bundle using the Eclipse Buddy Policy; additional resolvers can also be contributed using OSGi fragments.
Update: …
=> Allow configuring other strategies for finding the Google Cloud SDK.

src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
Recover missing tests.  PTAL @loosebazooka 
Fixes #183
=> Add tests for CloudSdk.Builder's use of resolvers

src/main/java/com/google/cloud/tools/appengine/cloudsdk/AppEngineJavaComponentsNotInstalledException.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkNotFoundException.java
@etanshaul @patflynn @loosebazooka @elharo 
I split the validation up into validating Cloud SDK separately from the Java components, and created a separate exception for when Cloud SDK is not found.
I also made the checks happen by default in the methods where the corresponding components are used.
=> Validate Cloud SDK and Java components before use

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java
See https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/937 on why this isn't needed anymore.
=> Remove unnecessary code.

src/main/java/com/google/cloud/tools/appengine/api/devserver/DefaultRunConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/devserver/RunConfiguration.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServerTest.java
This was motivated by https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/927. These changes allow callers to specify a java_home directory in the devserver `RunConfiguration`. 
Note that up until now, RunConfiguration has been used to only specify arguments to `dev_appserver.py`. This change would be the first environment variable that is added to the RunConfiguration interface - I think it's kind of nice to abstract that from the user a bit; I'm interested to hear other thoughts on that.
=> Make JAVA_HOME configurable on the devappserver child process

pom.xml
Since https://github.com/GoogleCloudPlatform/appengine-plugins-core/releases/tag/v0.1.11 has just been released.
=> Bump maven snapshot version to 0.1.12-SNAPSHOT

pom.xml
@meltsufin @patflynn @elharo 
I think we had misconfigured some scopes earlier.
I'm pretty sure about the junit scope change
findbugs to provided seems to be what the internet [says](http://stackoverflow.com/questions/26867614/what-is-correct-maven-scope-of-findbugs-annotations) is needed, however this I'm a lot less sure about. Findbugs annotation are only at compile time right, they're not preserved into runtime?
=> update dependency scopes

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
This is to fix https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/985 while the definite fix isn't in place.
=> Add environment variable on Windows to set file upload processes to 1

src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java
quick followup to https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/242
According to the Cloud SDK team, the cloud sdk version follows semantic versioning (see semver.org). This change is necessary so that parsing doesn't break if a pre-release version string is used, e.g. `0.1.0-rc1`.  
Note that with this change, any version suffix is simply ignored for comparison purposes. Full semver parsing and comparison will be implemented later.
=> Ignore suffixes

pom.xml
maven-bundle-plugin turns `${pom.organization.name}` &rarr; `Bundle-Vendor` ([source](http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#default-behavior))
Fixes #253
=> Set organization details

src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
Fixes #269.
Fixes #266.
It will be much much easier to understand the PR if you look at the changes incrementally made by the two commits: https://github.com/GoogleCloudPlatform/appengine-plugins-core/commit/374d4677cdff11fc770244574e25df4f6b971e56, https://github.com/GoogleCloudPlatform/appengine-plugins-core/commit/53b48c5f6b72b6c1cde9d09856b3d18b89e2b8c9
The first commit https://github.com/GoogleCloudPlatform/appengine-plugins-core/commit/374d4677cdff11fc770244574e25df4f6b971e56 joins the output handlers for `syncRun()`. As discussed in #269, the output handlers will be able to consume all (buffered) output of the sub-process until EOF and eventually die gracefully, [*even if the handlers start running well after the sub-process …
=> Wait for output handlers and fix asyncRun() code

pom.xml
Skipping 0.2.3-SNAPSHOT as we tagged two versions in a row (https://github.com/GoogleCloudPlatform/appengine-plugins-core/commit/2a09d26e06afefd9cdfa8b8174f4130637af70c7).
=> Bump version to 0.2.4-SNAPSHOT after 0.2.3 release

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
When many CloudSdk objects with different sdkPaths are created in quick succession, the values in JAR_LOCATIONS take a little while to update. This is creating some weirdness in IntelliJ when specifying different sdkPaths and validating them. All validations succeed, except for `if (!Files.isRegularFile(jarLocations.get(JAVA_TOOLS_JAR))) {` which still considers the old stored static sdkPath value and fails.
The visible impact of this in IntelliJ is that when an invalid path is changed to a valid one, the warning message doesn't disappear.
=> Makes JAR_LOCATIONS not static.

src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java
[The only method that can throw `IllegalThreadStateException` is `exitValue()`.](https://docs.oracle.com/javase/7/docs/api/java/lang/Process.htm) We don't have `exitValue()`.
=> Remove unnecessary exception catch

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkOutOfDateException.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkVersionFileNotFoundException.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
This PR makes a few enhancements to CloudSdk.getVersion that are required in order for the intellij plugin to use the version-compatibility logic in this library and not need to perform an expensive operation twice. (see https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1127 for more context).
Quick summary of changes:
- Cloud SDK version is now determined by reading the VERSION file at the root of the cloud sdk installation, rather than calling gcloud in a subprocess. This is more performant and the code is less complex. Note that this means we can't determine the version of any cloud sdk installation that is earlier than 133.0.0 (when VERSION files first started being used)
- CloudSdkOutOfDateException no longer inherits from CloudSdkNotFoundException. This makes it a …
=> Improve CloudSdk.getVersion

src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java
Update path resolver for look at /usr/bin directory. This patch fix CloudSdkNotFoundException related to official https://cloud.google.com/sdk/downloads Ubuntu/Debian apt-get install method. After installation, binaries are located at common /usr/bin/ directory.
=> Fix CloudSdkNotFoundException

src/main/java/com/google/cloud/tools/appengine/api/AppEngineException.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/AppEngineDeployment.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/AppEngineFlexibleStaging.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/AppEngineStandardStaging.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/DeployConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/StageFlexibleConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/StageStandardConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/devserver/AppEngineDevServer.java, src/main/java/com/google/cloud/tools/appengine/api/devserver/RunConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/devserver/StopConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/genconfig/GenConfigParams.java, src/main/java/com/google/cloud/tools/appengine/api/genconfig/GenConfigUtility.java, src/main/java/com/google/cloud/tools/appengine/api/whitelist/AppEngineJreWhitelist.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkResolver.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/DefaultProcessRunner.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/ProcessRunner.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/ProcessRunnerException.java, src/main/java/com/google/cloud/tools/project/package-info.java, src/test/java/com/google/cloud/tools/appengine/api/whitelist/AppEngineJreWhitelistTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkOutOfDateExceptionTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/PathResolverTest.java
- Some headers start with '/**'.
- Some files miss headers.
- Some files have the unnecessary `All Rights Reserved` phrase.
=> Fix copyright headers

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineVersions.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkResolver.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkVersionFileException.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkVersionFileNotFoundException.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkVersionFileParseException.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
@aslo @meltsufin Looking at this code for other reasons I realized that CT4E wasn't handling two of three possible failure modes because every mode has a different, unrelated, runtime exception type. The safest solution is to use  checked exceptions which would have turned our problems into compile time errors that were easily fixed. However as a stop gap use a single subclass of AppEngineException instead.
=> Single exception for version file problems

.travis.yml
I think we had this misconfigured. Currently travis is only running `test` from the `verify` stages. This enables all `verify` steps.
=> Make cobertuna run verify instead of just test

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java
A few bug fixes uncovered when trying to get the devappserver1 to work with CT4E.
- jvm flags need to be passed directly to the invoked JVM
- `--allow_remote_shutdown` isn't supported in Cloud SDK 144.0
- `--server` is to specify an update server; use `--address` and `--port`
PTAL @ludoch
=> Fix command-line generation for devappserver1

pom.xml
M2Eclipse is unable to use `errorprone` and must continue to use the JDT compiler.
=> Quell M2Eclipse errors from use of error prone

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer2.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer2Test.java
As discussed in https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/381#discussion_r113278236
I think this makes things a bit clearer
=> Rename devserver 2 classes to have "2"

kokoro/release_sign.sh, pom.xml
build scripts need to be located in the repository
no need for the gpg plugin in the pom as we use Kokoro to sign the jars
=> Fix release

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
fixes #425
This new parameter mimics the new gcloud configuration for providing the structured error logs environment variable setting `CLOUDSDK_CORE_SHOW_STRUCTURED_LOGS`.
gcloud accepts a string value for this: `terminal`, `log`, `always`, `never`
Setting this to terminal, or always, produces json output for messages coming from the cloudsdk according to the verbosity value currently set. 
**Example (consumed from IntelliJ):**
Without structured logs set (defaulted to `never`):
Same error, with verbosity  defaulted to `error`, and the structure logs parameter set to `log`:
=> Adds CloudSdk parameter for setting structured logs value

src/main/java/com/google/cloud/tools/appengine/api/devserver/DefaultRunConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/devserver/RunConfiguration.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer2.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer2Test.java
=> Add support to specify arbitrary arguments to devappserver

src/main/java/com/google/cloud/tools/appengine/cloudsdk/JsonParseException.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/AppEngineDeployResult.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/GcloudStructuredLog.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/AppEngineDeployResultTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/GcloudStructuredLogTest.java
- `AppEngineDeployResult` for the `gcloud app deploy` stdout, which contains the info about deployed apps.
- `GcloudStructuredLog` for structured log entries from `gcloud`
=> Add gcloud JSON output de-serialization classes

.travis.yml, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java
@chanseokoh @loosebazooka fix #450
=> set minimum version to 171.0

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java
Fixes #444 . 
Does this for CloudSdkAppEngineDevServer1. Will write the tests if this is the way we want to do it.
=> Adds GAE_ENV and GAE_RUNTIME environment variables for local development.

kokoro/release_publish.sh, kokoro/release_sign.sh
To fit the new build-sign-publish workflow.
Parallels https://github.com/GoogleCloudPlatform/app-maven-plugin/pull/209
=> Adds new Kokoro build script for publishing signed artifact to Sonatype.

pom.xml
Will output offending files.
User will still need to run `mvn fmt:format` to run auto formatter.
See https://github.com/coveo/fmt-maven-plugin/issues/18 for more info on help messaging.
=> Better error output from fmt:check

src/main/java/com/google/cloud/tools/managedcloudsdk/install/Downloader.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/Extractor.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/ExtractorFactory.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/Installer.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/InstallerFactory.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/DownloaderTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/ExtractorFactoryTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/ExtractorTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/InstallerTest.java
It turns out chaining callables wasn't the best idea, easier to just async once. This CL also adds some more checks and cleanup for different parts.
=> Remove unnecessary Callable interface. Fortify checks and cleanup.

src/main/java/com/google/cloud/tools/appengine/api/deploy/DefaultDeployProjectConfigurationConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/deploy/DeployProjectConfigurationConfiguration.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeployment.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDeploymentTest.java
This is for https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/231.
This adds the `DefaultDeployConfiguration#server` parameter to `DefaultDeployProjectConfigurationConfiguration`.
Will need to release a new version after this is pushed to be used in app-maven-plugin.
=> Adds --server parameter for deploying configuration YAML.

src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java
Hopefully this fixes the downgrade issue in the integration test.
=> Fix cloud SDK test, bug in Cloud SDK doesn't allow downgrades to 169

src/main/java/com/google/cloud/tools/managedcloudsdk/install/SdkInstaller.java
We construct `fileResourceProvider.getArchiveDestination()` so that it always returns either .tar.gz or .zip. See `FileResourceProviderFactory.newFileResourceProvider()` and `FileResourceProviderFactory.getVersionedFilename()`.
```java
return new FileResourceProvider(
new URL(LATEST_URL),
downloads.resolve("google-cloud-sdk.tar.gz"),
```
```java
private String getVersionedOsExtension() {
switch (os.name()) {
case WINDOWS:
return "windows-" + getArchitectureString() + ".zip";
case MAC:
return "darwin-" + getArchitectureString() + ".tar.gz";
case LINUX:
return "linux-" + getArchitectureString() + ".tar.gz";
default:
// we can't actually get here
throw new RuntimeException();
}
}
```
What do you think?
=> Swallow UnknownArchiveTypeException in SdkInstaller.install()

src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java, src/test/java/com/google/cloud/tools/libraries/json/CloudLibraryTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/OsInfoTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/VersionTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/command/CommandRunnerTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/components/SdkComponentInstallerTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/DownloaderTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/InstallerTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/SdkInstallerTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/process/ProcessExecutorTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/update/SdkUpdaterTest.java
Minor cleanups of upthrown exceptions and nullness warnings.  The `UnsupportedOsException`s are actually thrown in the `newManagedSdk()` variants, which must be called to obtain an `SdkInstaller`.
=> Clean up unthrown exceptions and nullness warnings

src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java, src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java
`ManagedCloudSdk#hasComponent()` uses `gcloud components list` to obtain the list of currently installed components, which causes a network access to fetch the latest component versions.  As noted in the code, Cloud SDK added a [`--only-local-state` flag in 170.0.0](https://cloud.google.com/sdk/docs/release-notes#google_cloud_sdk_4) to only list the locally-installed components and avoiding the network access.  Since our [minimum version is now 171.0.0](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java#L60), and our [`ManagedCloudSdkTests` tests against 174.0.0](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedClo …
=> Avoid network access when listing installed components

src/main/resources/com/google/cloud/tools/libraries/libraries.json
For whatever reason, this compute api is deprecated : details at https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2732
Offline discussion was to just remove this. Also I removed a bunch of trailing white spaces from this file.
=> Remove deprecated compute api from libraries.json

src/main/java/com/google/cloud/tools/managedcloudsdk/ChildProgressListener.java, src/main/java/com/google/cloud/tools/managedcloudsdk/ProgressListener.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/Extractor.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/ExtractorProvider.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/Installer.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/TarGzExtractorProvider.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/ZipExtractorProvider.java, src/test/java/com/google/cloud/tools/managedcloudsdk/ChildProgressListenerTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/NullProgressListener.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/ExtractorTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/InstallerTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/ProgressVerifier.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/TarGzExtractorProviderTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/ZipExtractorProviderTest.java
fixed #529 #528 
Provides a default implementation of a child progress listener. Implementers of progress listener should be able to just delegate to it for "newChild".
=> Add child progress listener and UNKNOWN const

.mvn/wrapper/maven-wrapper.properties, pom.xml
fixes #539
This PR will mandate all further tooling builds target java8 or higher.
=> Update build target to java8, maven version to 3.5.2

pom.xml
you can now run "checkstyle:check" and it will use the google style config.
the `<id>` tag doesn't do anything, so I removed them.
=> Fix checkstyle config

src/main/java/com/google/cloud/tools/appengine/cloudsdk/internal/process/ProcessBuilderFactory.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/LegacyProcessHandler.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/ProcessHandler.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/process/ProcessHandlerException.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/process/LegacyProcessHandlerTest.java
Adds in the processHandler() interface. This is what users must use to mimic the old behavior (allows for easier transition).
Generally this will look like
```
SomeOperationObject.doOperation(myCustomProcessHandler)
//or
SomeOperationObject.doOperations(legacyProcessHandler)
```
=> Add in process abstractions and legacy process handler for compatibility

src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java, src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java
About #595.
Reduces SDK home path length. With 20 more characters, I think we can practically get away from #595.
New: `Users\<user name>\AppData\Local\google\ct4j-cloud-sdk\LATEST\google-cloud-sdk`
Old: `Users\<user name>\AppData\Local\google-cloud-tools-java\managed-cloud-sdk\LATEST\google-cloud-sdk`
I also looked into if I could remove the last segment `google-cloud-sdk` too, but it is a bit complicated. Maybe next time if it still matters.
This will cause existing users to re-install the SDK on the new path. Because all our Cloud tools cannot be upgrade simultaneously (and even users may run multiple instances of Eclipses with different CT4E versions), we should not delete the old SDK install for some time. (For deleting in old SDK, I actually have a [working …
=> Reduce managed SDK install path length

src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/AppEngineDeployResult.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/GcloudStructuredLog.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/AppEngineDeployResultTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/GcloudStructuredLogTest.java
Our Javadoc:
```
* Parses a JSON string representing successful {@code gcloud app deploy} result.
*
* @return parsed JSON; never {@code null}
```
However, it turns out `Gson().fromJson()` does return null for empty JSON (not documented in the GSON Javadoc).
=> Fix nullability for JSON parsing

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdk.java
I've missed the discussion about making it public when we decided to remove the check from `validateCloudSdk()` in #442.
=> Make validateJdk public

.travis.yml, pom.xml
Fixes #623 
JaCoCo runs automatically on `mvn verify`, producing a binary report in `target/jacoco.exec`.
JaCoCo can be configured to fail the build if minimum requirements aren't met.
HTML reports can then be produced with `mvn jacoco:report`, put in `target/site/jacoco/jacoco-sessions.html`
=> Use JaCoCo instead of cobertura

src/test/java/com/google/cloud/tools/managedcloudsdk/command/AsyncByteConsumerTest.java
```
[DefaultCharset] Implicit use of the platform default charset, which can result in differing behaviour between JVM executions or incorrect behavior if the encoding of the data source doesn't match expectations.
(see http://errorprone.info/bugpattern/DefaultCharset)
Did you mean 'result.append(new String(bytes.getAllValues().get(i), 0, nBytes.getAllValues().get(i), UTF_8));' or 'result.append(new String(bytes.getAllValues().get(i), 0, nBytes.getAllValues().get(i), Charset.defaultCharset()));'?
```
=> Fix charset warning in test class

src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java, src/main/java/com/google/cloud/tools/managedcloudsdk/components/SdkComponentInstaller.java, src/main/java/com/google/cloud/tools/managedcloudsdk/components/SdkUpdater.java, src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/components/SdkComponentInstallerTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/components/SdkUpdaterTest.java
Fixes #651.
This is like executing the `gcloud` binary from the root directory.
=> Set root as working directory when updating Cloud SDK

src/test/java/com/google/cloud/tools/libraries/LibrariesTest.java
Saves almost 10 seconds on my machine.
Before:
```
Running com.google.cloud.tools.libraries.LibrariesTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.137 sec
```
After:
```
Running com.google.cloud.tools.libraries.LibrariesTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.436 sec
```
=> Make LibrariesTest#assertReachable use HEAD to avoid downloading full artifact

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStaging.java, src/main/java/com/google/cloud/tools/project/AppYaml.java, src/test/java/com/google/cloud/tools/appengine/AppEngineDescriptorTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineFlexibleStagingTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/GcloudRunnerTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/AppEngineDeployResultTest.java, src/test/java/com/google/cloud/tools/project/AppYamlTest.java
The PR enhances the `AppYaml` class to provide roughly the same functionality as the `AppEngineDescriptor` class.  
- I broke `AppYaml`'s constructor-based loader since it assumes the input comes from a file.  And active constructors aren't great.
- the only consumers of `AppYaml` outside of `appengine-plugins-core` is CT4E
- I wondered about moving `AppYaml` into `com.google.cloud.tools.appengine` to be alongside `AppEngineDescriptor`.  The `app.yaml` format doesn't seem to be used outside of App Engine, correct?
(Ideally `AppYaml` and `AppEngineDescriptor` would be a single POJO model object that could be loaded with either SnakeYAML or Jackson/Gson, but that involves quite a bit more work.  And surely there must be some code we can leverage somewhere?)
=> Enhance AppYaml

src/main/java/com/google/cloud/tools/managedcloudsdk/install/InstallScriptProvider.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/Installer.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/UnixInstallScriptProvider.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/WindowsInstallScriptProvider.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/InstallerTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/UnixInstallScriptProviderTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/WindowsInstallScriptProviderTest.java
Fixes #666.
It'd be ideal to avoid hard-coding the Cloud SDK home directory name (`google-cloud-sdk`) in the install script command line providers by dynamically identifying the extracted directory name and appending it to the command line, but due to the loose-coupling between the extractor, the command line provider, and the installer, that's pretty difficult. Not sure if it is really worth trying that.
=> Run script at parent directory of extracted Cloud SDK

pom.xml
Some tests take a while and it would be nice to be able to be able to exclude them for faster turnaround.  maven-surefire-plugin 2.19 or later supports a bang notation:
```
$ mvn -Dtest='!ManagedCloudSdkTest' verify
```
The two I've found useful:
- `ManagedCloudSdkTest`: if no Cloud SDK is available (e.g., running tests from a scratch docker instance), this test downloads and installs the Cloud SDK
- `LibrariesTest`: does a whole series of network calls
=> Update maven-surefire-plugin to allow excluding tests

pom.xml
Fixes missed package references as seen in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3165
=> Update maven-bundle-plugin to 3.5.0

src/main/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersion.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/serialization/CloudSdkVersionTest.java
Fixes #561.
I should say this may not be an ideal way to deal with HEAD. I've wondered what `getMajorVersion()` etc should return for HEAD, and after some tries, I ended up assigning the max int limit to the individual elements. This has the following consequences.
- A HEAD is just another regular version, nothing special, only having high numbers that are unsurpassable.
- When comparing recency, HEAD is always later (greater) than any non-HEAD version, although in reality this will not hold in most cases.
- One HEAD version is semantically equal to another HEAD version, although this will not be true in reality in almost all cases.
And I also need to verify if the content of the `VERSION` file is exactly `HEAD` without any surplus space.
=> Accept "HEAD" as CloudSdkVersion

src/main/java/com/google/cloud/tools/appengine/api/devserver/DefaultRunConfiguration.java, src/main/java/com/google/cloud/tools/appengine/api/devserver/RunConfiguration.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java, src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer2.java, src/test/java/com/google/cloud/tools/appengine/api/devserver/DefaultRunConfigurationTest.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer2Test.java
Fixes #567 
Next steps are to release a new version of `appengine-plugins-core` and use the new release in `app-maven-plugin` and `app-gradle-plugin`.
=> Passes --application flag to devappserver1 and 2.

src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1.java, src/test/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineDevServer1Test.java, src/test/resources/projects/EmptyStandard11Project/WEB-INF/appengine-web.xml
Minor fix to injected dev appserver variables.
Looks like kickstart might be doing this a little differently.
fixes #745
=> Update getGaeRuntime to handle java11

src/main/java/com/google/cloud/tools/appengine/operations/DevServers.java, src/test/java/com/google/cloud/tools/appengine/operations/DevServersRunnerTest.java, src/test/java/com/google/cloud/tools/appengine/operations/DevServersTest.java
LocalRun wasn't a good choice.
DevServers matches much better.
=> Rename LocalRun -> DevServers

.travis.yml, pom.xml
Trying out our build tools on Java 11. (Lot of changes based on https://github.com/GoogleContainerTools/jib/pull/1386)
=> Set up Travis build matrix to include OpenJDK 11 build / upgrade plugins

pom.xml
The `org.eclipse.m2e:lifecycle-mapping` plugin serves as a vehicle to provide configuration information to m2eclipse, and doesn't actually exist.  Move the plugin into an m2e-only profile to avoid spurious warnings.
Fix #774
=> Move m2e lifecycle-mapping into m2e-only profile to avoid spurious warnings

src/main/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStaging.java, src/test/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStagingTest.java
Probably should've had a test for this :\
=> Create parent if it doesn't exists when copying files

kokoro/continuous.bat, src/main/java/com/google/cloud/tools/managedcloudsdk/components/SdkComponent.java
gcloud now manages these extra components. Cloud Code is going to migrate to using the gcloud managed versions of these instead of using its own management system.
=> Add minikube and skaffold to list of gcloud components

src/main/java/com/google/cloud/tools/project/AppYaml.java, src/test/java/com/google/cloud/tools/project/AppYamlTest.java
part of #840 
also fixes some naming in tests.
NOTE: build is broken because of #841
=> Add entrypoint extraction to AppYaml parser

src/main/java/com/google/cloud/tools/appengine/configuration/AppYamlProjectStageConfiguration.java, src/main/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStaging.java, src/test/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStagingTest.java, src/test/java/com/google/cloud/tools/project/AppYamlTest.java
part of #840
requires #839
Allows binaries in java11 build path (for example when building a quarkus native app)
Also changes the deprecated use of appYamlStaging builder in tests
=> Add binary path to staging

kokoro/continuous.bat, src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/MessageCollector.java
Unblocks #851.
Also advances the fixed version to 314 for testing SDK upgrading. (As long as it's lower than the latest (currently 318), we should be good to test upgrading.)
=> Fix broken windows build by using Python3 for Cloud SDK

src/main/java/com/google/cloud/tools/managedcloudsdk/components/SdkComponent.java
Enabling Blueprints within the IDE requires the ability to download and manage kpt for the user. In Cloud Code for IntelliJ, we rely on the SdkComponent enum for installing managed dependencies via `gcloud components install <component>`. Therefore, we need to add kpt as an SdkComponent.
=> Add KPT to SdkComponent Enum

src/main/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdk.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/Installer.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/InstallerFactory.java, src/main/java/com/google/cloud/tools/managedcloudsdk/install/SdkInstaller.java, src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java, src/test/java/com/google/cloud/tools/managedcloudsdk/install/InstallerTest.java
Currently, the Managed Cloud SDK installer runs the installation script, which automatically installs the `["core", "gcloud-deps", "bq", "gcloud", "gsutil", "anthoscli", "kuberun"]` components. Of these, `anthoscli` and `kuberun` do not have native arm binaries and thus can only be installed if rosetta is installed.
For Cloud Code in IntelliJ, our goal for our March release is to not require the user to install rosetta in order to use our plugin. Allowing the client to specify the `--override-components` flag lets us specify which components we want to install while the offending components are updated (which may not be until after march)
* [kuberun cl](https://critique-ng.corp.google.com/cl/361621308)
* [anthoscli cl](https://gke-internal-review.googlesource.com/c/PaaSKit/anthos-cli/+/240 …
=> [ARM Support] Add support for override-components flag

src/main/java/com/google/cloud/tools/managedcloudsdk/components/SdkComponentInstaller.java
**Summary**
- [discussion context](https://github.com/GoogleCloudPlatform/cloud-code-intellij-internal/pull/3615#discussion_r590688062)
Followed the docs to update the command to accept multiple components during install
- https://cloud.google.com/sdk/gcloud/reference/components/install
- e.g. `gcloud components install alpha beta --quiet`
**Ran the following:**
- `mvn fmt:format`
- `mvn clean install -DskipTests`
- Could not get the tests to compile on a clean main branch, so skipped them
**Testing**
- Did not manually test yet
=> Adding support for installing multiple gcloud components

pom.xml
- Updating to 0.9.5
- [Release Instructions](https://g3doc.corp.google.com/company/teams/cloud-java/tools/developers/releasing.md?cl=head#releasing-via-rapid)
- Only merge after 0.9.4 is released: [build status](https://rapid.corp.google.com/#/release/cloud-java-tools-appengine-plugins-core-kokoro-release/v0.9.4?showInactive=false)
**TODO**
=> Release 0.9.4 Followup

src/test/java/com/google/cloud/tools/managedcloudsdk/ManagedCloudSdkTest.java
Can't be the latest version because `ManagedCloudSdkTest.testManagedCloudSdk_latest()` tries to "downgrade" to the fixed version, and then upgrades to latest, so they can't be the same.
=> Update gcloud to a recent version

src/main/java/com/google/cloud/tools/appengine/operations/cloudsdk/PathResolver.java
Fix following exception:
```
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
at java.base/java.lang.String.substring(String.java:1874)
at com.google.cloud.tools.appengine.operations.cloudsdk.PathResolver.unquote(PathResolver.java:119)
at com.google.cloud.tools.appengine.operations.cloudsdk.PathResolver.getLocationsFromPath(PathResolver.java:93)
```
=> Bugfix: fix `StringIndexOutOfBoundsException` from Crash report.

pom.xml, src/main/java/com/google/cloud/tools/appengine/operations/DevServer.java, src/test/java/com/google/cloud/tools/appengine/operations/DevServerJava8Test.java, src/test/java/com/google/cloud/tools/appengine/operations/DevServerJava9OrAboveTest.java
With this change, users won't have to specify their own add-opens in the applications that use appengine plugins.
I've split the Devserver tests into two versions, one for Java 8, and one for Java 9 and up.
Fixes #893.
=> Add extra JPMS open flags for Java 9 and up

pom.xml
upgrade to patched version for [vulnerability](https://github.com/advisories/GHSA-3mc7-4q67-w48m).
=> Update snakeyaml to 1.32

src/test/java/com/google/cloud/tools/managedcloudsdk/install/InstallerTest.java
Related to the Issue [#902](https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/902)
Flaky Test found using [NonDex](https://github.com/TestingResearchIllinois/NonDex) by running the command -
`mvn edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.google.cloud.tools.managedcloudsdk.install.InstallerTest#testCall_withOverrideComponents`
The logged failure for the test com.google.cloud.tools.managedcloudsdk.install.InstallerTest.testCall_withOverrideComponents -
```
[ERROR] Failures: 
[ERROR]   InstallerTest.testCall_withOverrideComponents:115 
Argument(s) are different! Wanted:
mockCommandRunner.run(
[scriptexec, test-install.script, --path-update=false, --command-completion=false, --quiet, --usage-reporting=true, --override-components, myothercomponent, …
```
=> Fix Flaky Test caused by HashSet Ordering permutations 

kokoro/continuous.bat
Resolves #911.
This PR logs the new environment's default `JAVA_HOME` (`C:\Program Files\Java\jdk1.8.0_211`) and removes the previously set location to resolve build error.
=> ci: fix kokoro windows build script

src/main/java/com/google/cloud/tools/appengine/configuration/RunConfiguration.java, src/main/java/com/google/cloud/tools/appengine/operations/DevServer.java, src/test/java/com/google/cloud/tools/appengine/operations/DevServerJava8Test.java, src/test/java/com/google/cloud/tools/appengine/operations/DevServerJava9OrAboveTest.java
Thank you for your interest in contributing! For general guidelines, please refer to
the [contributing guide](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/CONTRIBUTING.md).
Before submitting a pull request, please make sure to:
with your proposed change,
or [file a new issue](https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/new).
Allow users to allow a pass in the JDK version as part of the DevServer's Run Configurations. This may be different from the JDK specified in JAVA_HOME. By default, this plugin should generally be using the `java.specification.version` System Property. If needed, customers can use the Run Configuration's JDK version to override.
Fixes #916 🛠️
=> chore: Allow custom JDK version for Dev Server

.github/workflows/unit-tests.yaml, pom.xml, src/main/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStaging.java, src/main/java/com/google/cloud/tools/appengine/operations/DevAppServerRunner.java, src/test/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStagingTest.java, src/test/java/com/google/cloud/tools/appengine/operations/DevServersRunnerTest.java, src/test/java/com/google/cloud/tools/appengine/operations/cloudsdk/PathResolverTest.java
=> feat: support for java17 and java21 runtimes

kokoro/continuous.bat, kokoro/continuous.sh, kokoro/continuous_mac.sh, kokoro/release_build.sh, settings.xml
This will hopefully eliminate Maven artifact download flakiness in Kokoro CI jobs.
=> chore: add Google's Maven Central mirror

CONTRIBUTING.md
=> chore: updating contributing.md

app-gradle-plugin/USER_GUIDE.md
Fixes https://github.com/GoogleCloudPlatform/appengine-plugins/issues/1026
=> docs: add example of usage of extraFilesDirectories to gradle user guide

CONTRIBUTING.md
Following https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md
=> Update Contributing guideline for appengine plugins repo

appengine-plugins-core/src/main/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStaging.java, appengine-plugins-core/src/test/java/com/google/cloud/tools/appengine/operations/AppYamlProjectStagingTest.java
Fixes https://github.com/GoogleCloudPlatform/appengine-plugins/issues/1045
=> Adding a new runtimeID java25 to prepare the next GAE Java release for JDK25 support.
